### ISSUE TITLE
Convolve

### ISSUE THREAD

**Issue by wolftrax84** [nickrobinson/G729_CODE#32] opened 2011-01-20 22:07 UTC
filter.c

**Comment by nickrobinson** [comment] 2011-01-23 20:37
Working on this issue first seeing as Syn_filt seems to be more of a problem than originally thought.

**Comment by nickrobinson** [comment] 2011-01-27 14:15
I have just finished the convolve code and hope to get the memory hooked up for testing this afternoon.

**Comment by nickrobinson** [comment] 2011-02-04 20:25
Finished the Convolve function and have added test files. Closed by ad0b3d1035abd1e184095bad8b35ef5abe8197d8

**Comment by nickrobinson** [comment] 2011-02-04 20:41
I have completed this function and below is a sample of my output. I am having collision errors, and am not quite sure what this means? Did we ever get an answer on this jpj79?

```
blk_mem_gen_v2_4 collision detected at time: 571810000, A write address: 0, B  ra`d address: 0
        blk_mem_gen_v2_4 collision detected at time: 572010000, A write address: 280, B  ra`d address: 280
        blk_mem_gen_v2_4 collision detected at time: 572270000, A write address: 281, B  ra`d address: 281
        blk_mem_gen_v2_4 collision detected at time: 572590000, A write address: 282, B  ra`d address: 282
        blk_mem_gen_v2_4 collision detected at time: 572970000, A write address: 283, B  ra`d address: 283
        blk_mem_gen_v2_4 collision detected at time: 573410000, A write address: 284, B  ra`d address: 284
        blk_mem_gen_v2_4 collision detected at time: 573910000, A write address: 285, B  ra`d address: 285
        blk_mem_gen_v2_4 collision detected at time: 574470000, A write address: 286, B  ra`d address: 286
        blk_mem_gen_v2_4 collision detected at time: 575090000, A write address: 287, B  ra`d address: 287
        blk_mem_gen_v2_4 collision detected at time: 575770000, A write address: 288, B  ra`d address: 288
        blk_mem_gen_v2_4 collision detected at time: 576510000, A write address: 289, B  ra`d address: 289
        blk_mem_gen_v2_4 collision detected at time: 577310000, A write address: 28a, B  ra`d address: 28a
        blk_mem_gen_v2_4 collision detected at time: 578170000, A write address: 28b, B  ra`d address: 28b
        blk_mem_gen_v2_4 collision detected at time: 579090000, A write address: 28c, B  ra`d address: 28c
        blk_mem_gen_v2_4 collision detected at time: 580070000, A write address: 28d, B  ra`d address: 28d
        blk_mem_gen_v2_4 collision detected at time: 581110000, A write address: 28e, B  ra`d address: 28e
        blk_mem_gen_v2_4 collision detected at time: 582210000, A write address: 28f, B  ra`d address: 28f
        blk_mem_gen_v2_4 collision detected at time: 583370000, A write address: 290, B  ra`d address: 290
        blk_mem_gen_v2_4 collision detected at time: 584590000, A write address: 291, B  ra`d address: 291
        blk_mem_gen_v2_4 collision detected at time: 585870000, A write address: 292, B  ra`d address: 292
        blk_mem_gen_v2_4 collision detected at time: 587210000, A write address: 293, B  ra`d address: 293
        blk_mem_gen_v2_4 collision detected at time: 588610000, A write address: 294, B  ra`d address: 294
        blk_mem_gen_v2_4 collision detected at time: 590070000, A write address: 295, B  ra`d address: 295
        blk_mem_gen_v2_4 collision detected at time: 591590000, A write address: 296, B  ra`d address: 296
        blk_mem_gen_v2_4 collision detected at time: 593170000, A write address: 297, B  ra`d address: 297
        blk_mem_gen_v2_4 collision detected at time: 594810000, A write address: 298, B  ra`d address: 298
        blk_mem_gen_v2_4 collision detected at time: 596510000, A write address: 299, B  ra`d address: 299
        blk_mem_gen_v2_4 collision detected at time: 598270000, A write address: 29a, B  ra`d address: 29a
        blk_mem_gen_v2_4 collision detected at time: 600090000, A write address: 29b, B  ra`d address: 29b
        blk_mem_gen_v2_4 collision detected at time: 601970000, A write address: 29c, B  ra`d address: 29c
        blk_mem_gen_v2_4 collision detected at time: 603910000, A write address: 29d, B  ra`d address: 29d
        blk_mem_gen_v2_4 collision detected at time: 605910000, A write address: 29e, B  ra`d address: 29e
        blk_mem_gen_v2_4 collision detected at time: 607970000, A write address: 29f, B  ra`d address: 29f
        blk_mem_gen_v2_4 collision detected at time: 610090000, A write address: 2a0, B  ra`d address: 2a0
        blk_mem_gen_v2_4 collision detected at time: 612270000, A write address: 2a1, B  ra`d address: 2a1
        blk_mem_gen_v2_4 collision detected at time: 614510000, A write address: 2a2, B  ra`d address: 2a2
        blk_mem_gen_v2_4 collision detected at time: 616810000, A write address: 2a3, B  ra`d address: 2a3
        blk_mem_gen_v2_4 collision detected at time: 619170000, A write address: 2a4, B  ra`d address: 2a4
        blk_mem_gen_v2_4 collision detected at time: 621590000, A write address: 2a5, B  ra`d address: 2a5
        blk_mem_gen_v2_4 collision detected at time: 624070000, A write address: 2a6, B  ra`d address: 2a6
        blk_mem_gen_v2_4 collision detected at time: 626610000, A write address: 2a7, B  ra`d address: 2a7
          626650 CORRECT:  r'[        360] = 0000003e
          626690 CORRECT:  r'[        361] = 00000279
          626730 CORRECT:  r'[        362] = 0000fdc1
          626770 CORRECT:  r'[        363] = 00000025
          626810 CORRECT:  r'[        364] = 00000137
          626850 CORRECT:  r'[        365] = 0000ff03
          626890 CORRECT:  r'[        366] = 00000031
          626930 CORRECT:  r'[        367] = 0000ffad
          626970 CORRECT:  r'[        368] = 000000b4
          627010 CORRECT:  r'[        369] = 000001a7
          627050 CORRECT:  r'[        370] = 0000fe7b
          627090 CORRECT:  r'[        371] = 00000006
          627130 CORRECT:  r'[        372] = 000000ba
          627170 CORRECT:  r'[        373] = 0000ffaa
          627210 CORRECT:  r'[        374] = 0000ffef
          627250 CORRECT:  r'[        375] = 0000ff89
          627290 CORRECT:  r'[        376] = 00000115
          627330 CORRECT:  r'[        377] = 00000157
          627370 CORRECT:  r'[        378] = 0000fdfc
          627410 CORRECT:  r'[        379] = 0000009b
          627450 CORRECT:  r'[        380] = 00000095
          627490 CORRECT:  r'[        381] = 0000ff81
          627530 CORRECT:  r'[        382] = 0000007b
          627570 CORRECT:  r'[        383] = 0000ff4a
          627610 CORRECT:  r'[        384] = 000000e2
          627650 CORRECT:  r'[        385] = 0000011b
          627690 CORRECT:  r'[        386] = 0000fe42
          627730 CORRECT:  r'[        387] = 00000087
          627770 CORRECT:  r'[        388] = 00000060
          627810 CORRECT:  r'[        389] = 0000ffd4
          627850 CORRECT:  r'[        390] = 00000060
          627890 CORRECT:  r'[        391] = 0000ff7e
          627930 CORRECT:  r'[        392] = 000000d8
          627970 CORRECT:  r'[        393] = 00000194
          628010 CORRECT:  r'[        394] = 0000febb
          628050 CORRECT:  r'[        395] = 0000ffa4
          628090 CORRECT:  r'[        396] = 000000fb
          628130 CORRECT:  r'[        397] = 0000ff90
          628170 CORRECT:  r'[        398] = 0000ffc9
          628210 CORRECT:  r'[        399] = 0000ffb7
```

**Comment by thrawn117** [comment] 2011-02-04 22:49
So far as I can tell, its a non-issue.
I say that because it doesn't affect the performance of the modules.
Nice work BTW.

**Comment by thrawn117** [comment] 2011-02-05 22:14
1. I looked at your FSM for Convolve and overall, it looked good. But your memory accessing for this module is gonna have to be changed a little bit.  Remind me to show you next time we're in lab.
2. I'll also have to show you how we're gonna change up our testing just a little bit for Parker's sake.

**Comment by nickrobinson** [comment] 2011-02-10 13:39
Parker, I have updated this code so you should be able to perform testing correctly at this point. Let me know if you run into any problems.

**Comment by nickrobinson** [comment] 2011-02-18 01:13
Clock cycle estimate: 1880 clock cycles
This function is called twice which will lead to a total predicted clock cycles of: 3760

**Comment by jpj79** [comment] 2011-02-26 22:33
For this code do you have a top level and a data path? or is there a data path by chance you haven't put on the repository? I can build one if needed but I can't test it until then. Let me know if there are some files just not on the repository or if we need to create some instead.

**Comment by nickrobinson** [comment] 2011-02-26 22:39
I did not write a top level or a datapath when I originally wrote this module. If you need me to write one I can, but it will have to be after I get select 1 & 2 checked in. Let me know what would work best for you.

**Comment by jpj79** [comment] 2011-02-26 23:06
I will work on one this evening. I am taking notes on everyone's files currently.

**Comment by jpj79** [comment] 2011-02-28 05:16
I have it running in Post-Route. I spent a few hours trying to correct an error I introduced when I added the top-level and pipe. The code is currently generating timing violations. I believe they are being caused by the read and write addresses being tied to the same signal. I will have more details on it tomorrow

**Comment by jpj79** [comment] 2011-02-28 19:47
Convolve runs at 50 MHz with all correct outputs and no timing violations exist anymore.

**Closed as completed** 2011-03-01 03:47 UTC
Labels: Nick, Parker

**Comment by jpj79** [comment] 2011-03-01 20:36
Convolve has passed all tests at 100 MHz.

**Comment by jpj79** [comment] 2011-03-03 20:31
Convolve used 2742 clock cycles from start to done during simulation at 50 MHz

**Comment by jpj79** [comment] 2011-04-19 22:24
Behavioral Timing Samples:
START: 6510 ns
DONE: 61,330 ns
TOTAL: 2741 Clock cycles

START: 446,530 ns
DONE: 501,350 ns
TOTAL: 2741 Clock Cycles
